In [1066]:
#IMPORTING LIBRARIES
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
!pip install graphviz python-graphviz
!pip3 install keras
!pip3 install ann_visualizer
!pip install graphviz

ERROR: Could not find a version that satisfies the requirement python-graphviz (from versions: none)
ERROR: No matching distribution found for python-graphviz


In [1067]:
#IMPORTING THE DATASET
dataset = pd.read_excel('input_female.xlsx')
pd.set_option('max_rows', 99999)
pd.set_option('max_colwidth', 400)
pd.describe_option('max_colwidth')

display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: 400]


In [1068]:
print(dataset)

    Catergory  Ferritin    FSH  ...  Progesterone   MDA   Protein Carbonyl
0           1      2245   1.06  ...          1.57  12.37              1.47
1           1      2368   1.96  ...          1.19  11.69              2.07
2           1      2361   0.59  ...          1.21  13.69              2.61
3           1      1700   5.27  ...          1.16   9.20              1.63
4           1      6214   3.41  ...          0.29  14.35              2.09
5           1      1607   7.68  ...          2.20   7.28              1.63
6           1      2629   1.03  ...          3.29  13.05              2.33
7           1      6041   0.21  ...          0.65  13.74              2.20
8           1      2789   2.38  ...          0.84  12.57              1.99
9           1      1840   2.38  ...          2.09   9.20              1.92
10          1      2313   1.37  ...          2.14  11.03              1.72
11          1      2846   0.04  ...          0.54  13.20              1.86
12          1      2980  

In [1069]:
#VALIDATION DATASET
dataset_validation=dataset.sample(frac=0.18, random_state=10)

In [1070]:
print(dataset_validation)

    Catergory  Ferritin    FSH  ...  Progesterone   MDA   Protein Carbonyl
20          1      3877   0.19  ...          1.24  13.87              2.16
3           1      1700   5.27  ...          1.16   9.20              1.63
46          2        27   6.20  ...          6.99   1.54              1.17
17          1      6170   0.06  ...          0.55  14.36              2.21
31          2        47   1.03  ...          5.45   6.81              0.78
35          2        43  20.65  ...          9.45   5.00              0.82
39          2        13   6.30  ...          7.46   6.15              1.10
26          1      4160   0.56  ...          0.46  16.28              2.47
21          1      3690   0.53  ...          0.10  13.63              2.41
38          2        60   3.90  ...          4.72   4.29              0.81

[10 rows x 8 columns]


In [1071]:
#TRAINING DATASET
np.random.seed(10)
remove_n = 10
drop_indices = np.random.choice(dataset.index, remove_n, replace=False)
dataset_training = dataset.drop(drop_indices)

In [1072]:
print(dataset_training)

    Catergory  Ferritin    FSH  ...  Progesterone   MDA   Protein Carbonyl
0           1      2245   1.06  ...          1.57  12.37              1.47
1           1      2368   1.96  ...          1.19  11.69              2.07
2           1      2361   0.59  ...          1.21  13.69              2.61
4           1      6214   3.41  ...          0.29  14.35              2.09
5           1      1607   7.68  ...          2.20   7.28              1.63
6           1      2629   1.03  ...          3.29  13.05              2.33
7           1      6041   0.21  ...          0.65  13.74              2.20
8           1      2789   2.38  ...          0.84  12.57              1.99
9           1      1840   2.38  ...          2.09   9.20              1.92
10          1      2313   1.37  ...          2.14  11.03              1.72
11          1      2846   0.04  ...          0.54  13.20              1.86
12          1      2980   0.95  ...          2.59  10.46              2.01
13          1      1689  

In [1073]:
X = dataset_training.iloc[:,1:6].values
y = dataset_training.iloc[:, 6:].values

In [1074]:
print(X)

[[2.24e+03 1.06e+00 1.66e+00 1.65e+00 1.57e+00]
 [2.37e+03 1.96e+00 1.21e+00 7.56e+00 1.19e+00]
 [2.36e+03 5.90e-01 3.90e-01 7.69e+00 1.21e+00]
 [6.21e+03 3.41e+00 3.30e-01 6.80e-01 2.90e-01]
 [1.61e+03 7.68e+00 8.40e+00 8.29e+00 2.20e+00]
 [2.63e+03 1.03e+00 1.50e+00 3.38e+00 3.29e+00]
 [6.04e+03 2.10e-01 4.00e-01 4.11e+00 6.50e-01]
 [2.79e+03 2.38e+00 7.90e-01 9.10e-01 8.40e-01]
 [1.84e+03 2.38e+00 1.00e+00 8.62e+00 2.09e+00]
 [2.31e+03 1.37e+00 5.90e-01 1.96e+00 2.14e+00]
 [2.85e+03 4.00e-02 3.60e-01 2.19e+00 5.40e-01]
 [2.98e+03 9.50e-01 3.07e+00 1.01e+00 2.59e+00]
 [1.69e+03 3.93e+00 3.81e+00 2.65e+01 2.94e+00]
 [2.83e+03 7.67e+00 2.17e+00 1.02e+01 1.47e+00]
 [2.68e+03 8.62e+00 3.31e+00 1.40e+01 1.45e+00]
 [3.39e+03 6.10e+00 8.00e-01 8.32e+00 1.70e-01]
 [2.34e+03 1.19e+00 1.20e-01 5.09e+00 4.60e-01]
 [2.24e+03 3.20e-01 8.90e-01 4.86e+00 3.60e-01]
 [4.51e+03 1.79e+00 9.20e-01 2.56e+00 2.00e-01]
 [1.81e+03 6.20e-01 3.00e-01 3.88e+00 4.50e-01]
 [2.71e+03 1.31e+00 7.60e-01 3.89e+00 1.

In [1075]:
print(y)

[[12.37  1.47]
 [11.69  2.07]
 [13.69  2.61]
 [14.35  2.09]
 [ 7.28  1.63]
 [13.05  2.33]
 [13.74  2.2 ]
 [12.57  1.99]
 [ 9.2   1.92]
 [11.03  1.72]
 [13.2   1.86]
 [10.46  2.01]
 [ 7.32  1.75]
 [ 9.11  1.93]
 [10.28  1.6 ]
 [10.85  2.04]
 [11.77  2.05]
 [11.8   1.48]
 [14.22  2.15]
 [12.51  1.85]
 [12.94  2.35]
 [13.55  2.33]
 [ 9.63  1.84]
 [ 5.35  0.77]
 [ 2.1   0.74]
 [ 6.41  0.85]
 [ 5.57  0.85]
 [ 4.83  0.81]
 [ 4.46  0.9 ]
 [ 2.9   1.28]
 [ 2.26  0.72]
 [ 4.87  1.11]
 [ 5.38  1.26]
 [ 5.96  1.01]
 [ 2.95  1.  ]
 [ 2.51  1.23]
 [ 3.46  1.16]
 [ 2.63  1.05]
 [ 2.18  0.9 ]
 [ 3.14  0.91]
 [ 1.79  1.02]
 [ 6.47  1.09]
 [ 4.15  1.01]
 [ 5.7   1.02]
 [ 3.46  0.91]]


In [1076]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [1077]:
print(X_test)

[[7.90e+01 2.40e+00 3.90e+00 4.01e+01 4.08e+00]
 [8.70e+01 8.20e+00 1.53e+01 2.14e+01 2.06e+00]
 [2.30e+01 6.50e+00 5.20e+00 3.65e+01 7.46e+00]
 [1.61e+03 7.68e+00 8.40e+00 8.29e+00 2.20e+00]
 [2.85e+03 4.00e-02 3.60e-01 2.19e+00 5.40e-01]
 [8.40e+01 8.68e+00 2.07e+00 1.30e+01 9.12e+00]
 [1.61e+02 6.90e+00 1.39e+01 2.56e+01 4.00e+00]
 [2.98e+03 9.50e-01 3.07e+00 1.01e+00 2.59e+00]
 [9.40e+01 1.01e+01 1.24e+01 9.74e+01 1.75e+01]
 [4.00e+01 6.90e+00 1.28e+01 6.23e+01 1.28e+00]
 [6.40e+01 4.01e+00 6.96e+00 2.04e+01 8.42e+00]
 [2.71e+03 1.31e+00 7.60e-01 3.89e+00 1.03e+00]]


In [1078]:
#FEATURE SELECTION
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [1079]:
import tensorflow as tf

In [1080]:
## Initializing the ANN
ann = tf.keras.models.Sequential()

In [1081]:
### Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=40, activation='tanh'))

In [1082]:
### Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=40, activation='tanh'))

In [1083]:
### Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=40, activation='tanh'))

In [1084]:
### Adding the output layer
ann.add(tf.keras.layers.Dense(units=2))

In [1085]:
### Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')


In [1086]:
### Training the ANN model on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs =800)

Epoch 1/800
2/2 [==============================] - 0s 3ms/step - loss: 47.1439
Epoch 2/800
2/2 [==============================] - 0s 3ms/step - loss: 45.5161
Epoch 3/800
2/2 [==============================] - 0s 3ms/step - loss: 44.3964
Epoch 4/800
2/2 [==============================] - 0s 3ms/step - loss: 43.6153
Epoch 5/800
2/2 [==============================] - 0s 3ms/step - loss: 42.5994
Epoch 6/800
2/2 [==============================] - 0s 3ms/step - loss: 42.1280
Epoch 7/800
2/2 [==============================] - 0s 3ms/step - loss: 40.4484
Epoch 8/800
2/2 [==============================] - 0s 4ms/step - loss: 40.1769
Epoch 9/800
2/2 [==============================] - 0s 4ms/step - loss: 39.7656
Epoch 10/800
2/2 [==============================] - 0s 3ms/step - loss: 38.6438
Epoch 11/800
2/2 [==============================] - 0s 2ms/step - loss: 38.3780
Epoch 12/800
2/2 [==============================] - 0s 3ms/step - loss: 38.0247
Epoch 13/800
2/2 [==============================]

In [1087]:
from ann_visualizer.visualize import ann_viz;


ann_viz(ann, view=True)

In [1088]:
### Predicting the results of the Test set
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
y_pred

array([[ 3.46,  1.29],
       [ 3.95,  1.05],
       [ 4.49,  1.14],
       [ 7.98,  1.65],
       [12.84,  2.13],
       [ 4.99,  0.85],
       [ 5.07,  1.27],
       [13.22,  2.11],
       [ 5.79,  1.24],
       [ 2.91,  1.26],
       [ 7.3 ,  1.11],
       [12.5 ,  2.09]], dtype=float32)

In [1089]:
concat=np.column_stack((X_test,y_pred))
df = pd.DataFrame(concat)
display(df)

0         1         2         3         4          5         6
0  -0.958907 -0.723270 -0.125372  0.915032  0.093979   3.463355  1.289932
1  -0.954205  0.719200  2.332419  0.110926 -0.401641   3.946623  1.050928
2  -0.991819  0.296407  0.154902  0.761808  0.923284   4.490997  1.138083
3  -0.060873  0.589875  0.844808 -0.457085 -0.367291   7.982546  1.653716
4   0.667310 -1.310206 -0.888581 -0.720372 -0.774583  12.839021  2.133776
5  -0.955969  0.838577 -0.519912 -0.253792  1.330576   4.994721  0.845793
6  -0.910714  0.395888  2.030585  0.288753  0.074350   5.066572  1.269643
7   0.746064 -1.083887 -0.304317 -0.771303 -0.271602  13.217322  2.108182
8  -0.950091  1.191733  1.707191  3.390799  3.384210   5.790958  1.237115
9  -0.981828  0.395888  1.793430  1.872795 -0.593019   2.909897  1.263045
10 -0.967723 -0.322860  0.534351  0.063880  1.158826   7.298031  1.113999
11  0.587380 -0.994355 -0.802343 -0.646997 -0.654358  12.500495  2.090570

In [1090]:
#PREDICTING THE TRAINING SET RESULTS
y_pred3 = ann.predict(X_train)
print(y_pred3)

[[ 5.91  1.14]
 [11.81  2.02]
 [ 5.51  1.17]
 [13.82  2.25]
 [11.47  2.05]
 [10.68  1.62]
 [11.68  2.05]
 [ 3.79  1.04]
 [10.31  1.82]
 [10.01  1.84]
 [12.39  1.94]
 [11.96  2.08]
 [ 5.57  1.28]
 [ 9.15  1.8 ]
 [ 3.26  1.24]
 [12.43  2.08]
 [ 4.04  1.18]
 [11.76  2.03]
 [ 4.51  0.93]
 [ 8.71  1.68]
 [ 3.67  1.16]
 [ 2.63  0.81]
 [14.19  2.29]
 [ 3.74  0.77]
 [ 3.48  0.92]
 [12.89  2.12]
 [10.91  1.98]
 [11.87  1.94]
 [ 4.59  1.25]
 [ 4.62  1.17]
 [14.14  2.27]
 [12.2   2.02]
 [ 3.95  1.1 ]]


In [1091]:
concat2=np.column_stack((X_train,y_pred3))
df2 = pd.DataFrame(concat2)
display(df2)

0         1         2         3         4          5         6
0  -0.947153  0.221797  0.499855  0.411333  0.918377   5.913734  1.144635
1   0.382266 -1.173420 -0.882113 -0.482982 -0.610194  11.805993  2.018216
2  -0.958907  1.092253  0.844808  1.401035  1.764857   5.510431  1.172409
3   1.642922 -0.874978 -0.767847 -0.704402 -0.858004  13.823232  2.247020
4   0.984678  0.196927 -0.793719 -0.455790 -0.865365  11.467731  2.048021
5   0.251205 -0.735705 -0.741976 -0.551609  0.174947  10.681852  1.622838
6   0.369336 -1.024199 -0.940324 -0.595203 -0.794212  11.679513  2.053718
7  -0.945977  0.744070  2.591134  0.436798 -0.453166   3.789718  1.041004
8   0.076065 -0.728244 -0.750600 -0.442841 -0.394280  10.305936  1.818679
9   0.659082  0.587388 -0.498353 -0.375077 -0.546401  10.005314  1.844118
10  0.539775 -1.063991 -0.642802 -0.669009 -0.099853  12.391681  1.936958
11  0.308214 -1.240569 -0.774315 -0.605130 -0.818747  11.957098  2.076576
12 -1.000047  2.111930  1.448476  3.518126  3.617298   5.566473  1.280232
13  0.570336  0.823655 -0.252574 -0.211493 -0.551309   9.154433  1.802366
14 -0.958319 -0.101516  0.586094  1.503329  0.255914   3.263748  1.244877
15  0.633810 -0.728244 -0.795875 -0.775619 -0.700976  12.430139  2.083903
16 -0.948916  0.395888  1.383798 -0.225305 -0.600380   4.039505  1.183322
17  0.386380 -0.832699 -0.705325 -0.488593 -0.615101  11.760461  2.033388
18 -0.983591  1.117123  0.586094 -0.702676  0.417850   4.510691  0.925951
19 -0.012680 -0.342756 -0.144776  0.329757 -0.185727   8.711423  1.681034
20 -0.983004  0.843551  1.944347  0.534776 -0.433537   3.672150  1.161026
21 -0.985354  1.196708 -0.213766 -0.328030  0.523353   2.630672  0.806428
22  2.545070 -1.267927 -0.879957 -0.637501 -0.747594  14.193826  2.285327
23 -0.944802  1.266344 -0.332344 -0.545566  0.886480   3.741940  0.765948
24 -0.968898  1.191733  0.650772 -0.105315  0.280450   3.484169  0.916630
25  0.767810 -1.103784 -0.895049 -0.713035 -0.666626  12.888890  2.124032
26  0.060197 -1.165959 -0.901517 -0.647428 -0.796665  10.913083  1.980454
27  0.354056 -0.979433 -0.838994 -0.730299 -0.382013  11.873166  1.937604
28 -0.959495  0.843551  1.965906  0.773030  0.233832   4.591721  1.251863
29 -0.933635  0.395888  0.629213  2.473177  2.125531   4.620269  1.169306
30  2.646745 -0.472081 -0.895049 -0.785547 -0.835922  14.137693  2.273015
31  0.314091 -1.056530 -0.608307 -0.743680 -0.521866  12.198519  2.024487
32 -0.961258  1.863228  1.125083  1.140769  1.279051   3.953782  1.103089

In [1092]:
#PREDICTING A NEW RESULT
print(ann.predict(sc.transform([[6041,0.21,0.4,4.11,0.66]])))

[[14.19  2.29]]


In [1093]:
#PREDICTING A NEW RESULT
print(ann.predict(sc.transform([[1700,5.27,1.06,20.64,1.16]])))

[[7.   1.75]]


In [1094]:
from sklearn.metrics import mean_squared_error as MSE 
rmse = np.sqrt(MSE(y_test, y_pred)) 
print("RMSE : % f" %(rmse)) 

RMSE :  1.460554


In [1095]:
from sklearn.metrics import r2_score 
r2 = r2_score(y_test, y_pred) 
print("R^2 : % f" %(r2))

R^2 :  0.719524


In [1096]:
from sklearn.metrics import mean_squared_error as MSE 
rmse = np.sqrt(MSE(y_train, y_pred3)) 
print("RMSE : % f" %(rmse)) 

RMSE :  0.724061


In [1097]:
from sklearn.metrics import r2_score 
r4 = r2_score(y_train, y_pred3) 
print("R^2 : % f" %(r4))

R^2 :  0.877030
