In [762]:
#IMPORTING LIBRARIES
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
!pip install graphviz python-graphviz

!pip3 install keras
!pip3 install ann_visualizer
!pip install graphviz

ERROR: Could not find a version that satisfies the requirement python-graphviz (from versions: none)
ERROR: No matching distribution found for python-graphviz


In [763]:
#IMPORTING THE DATASET
dataset = pd.read_excel('input_male.xlsx')
pd.set_option('max_rows', 99999)
pd.set_option('max_colwidth', 400)
pd.describe_option('max_colwidth')

display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: 400]


In [764]:
print(dataset)

    Caterory  Ferritin    FSH     LH  Testosterone    MDA    PC
0          1      1598   2.69   0.56          1.71  10.13  1.69
1          1      1436   5.29   0.64          2.18   8.50  1.44
2          1      3672   1.32   1.17          1.46  11.09  2.08
3          1      3013   0.77   1.19          1.56  13.66  2.06
4          1      4934   0.14   0.52          1.52  15.77  2.65
5          1      5320   0.10   0.10          0.49  16.86  2.11
6          1      3546   1.67   0.51          0.25  15.32  2.43
7          1      3305   0.26   1.01          1.61  12.92  2.35
8          1      6318   0.39   0.08          0.45  17.55  2.62
9          1      4420   0.34   1.95          2.43  12.41  2.43
10         1      1744   4.55   1.26          2.76   9.70  2.28
11         1      3832   4.72   1.25          1.73  11.10  2.01
12         1      2435   1.75   1.09          3.29  11.69  1.61
13         1      4832   1.46   0.48          0.23  15.13  2.08
14         1      3740   1.18   1.12    

In [765]:
#VALIDATION DATASET
dataset_validation=dataset.sample(frac=0.18, random_state=10)

In [766]:
print(dataset_validation)

    Caterory  Ferritin   FSH     LH  Testosterone    MDA    PC
37         2       121  2.80   8.50          3.08   2.12  0.80
23         1      3439  0.94   0.79          3.87  13.97  2.28
44         2       140  7.90   9.90          5.31   2.44  0.86
42         2        39  7.80  12.60         12.38   1.99  0.87
47         2        37  7.30   5.10          8.37   1.86  0.88
20         1      1684  1.46   0.98          4.64  10.51  1.57
3          1      3013  0.77   1.19          1.56  13.66  2.06
30         2        26  5.18   7.25          3.95   3.28  0.78
7          1      3305  0.26   1.01          1.61  12.92  2.35


In [767]:
print(dataset)

    Caterory  Ferritin    FSH     LH  Testosterone    MDA    PC
0          1      1598   2.69   0.56          1.71  10.13  1.69
1          1      1436   5.29   0.64          2.18   8.50  1.44
2          1      3672   1.32   1.17          1.46  11.09  2.08
3          1      3013   0.77   1.19          1.56  13.66  2.06
4          1      4934   0.14   0.52          1.52  15.77  2.65
5          1      5320   0.10   0.10          0.49  16.86  2.11
6          1      3546   1.67   0.51          0.25  15.32  2.43
7          1      3305   0.26   1.01          1.61  12.92  2.35
8          1      6318   0.39   0.08          0.45  17.55  2.62
9          1      4420   0.34   1.95          2.43  12.41  2.43
10         1      1744   4.55   1.26          2.76   9.70  2.28
11         1      3832   4.72   1.25          1.73  11.10  2.01
12         1      2435   1.75   1.09          3.29  11.69  1.61
13         1      4832   1.46   0.48          0.23  15.13  2.08
14         1      3740   1.18   1.12    

In [768]:
#TRAINING DATASET
np.random.seed(10)
remove_n = 10
drop_indices = np.random.choice(dataset.index, remove_n, replace=False)
dataset_training = dataset.drop(drop_indices)

In [769]:
print(dataset_training)

    Caterory  Ferritin    FSH     LH  Testosterone    MDA    PC
0          1      1598   2.69   0.56          1.71  10.13  1.69
1          1      1436   5.29   0.64          2.18   8.50  1.44
2          1      3672   1.32   1.17          1.46  11.09  2.08
4          1      4934   0.14   0.52          1.52  15.77  2.65
5          1      5320   0.10   0.10          0.49  16.86  2.11
8          1      6318   0.39   0.08          0.45  17.55  2.62
9          1      4420   0.34   1.95          2.43  12.41  2.43
10         1      1744   4.55   1.26          2.76   9.70  2.28
11         1      3832   4.72   1.25          1.73  11.10  2.01
12         1      2435   1.75   1.09          3.29  11.69  1.61
13         1      4832   1.46   0.48          0.23  15.13  2.08
14         1      3740   1.18   1.12          1.46   9.37  1.95
15         1      3846   4.81   0.93          1.63  14.49  2.58
16         1      4739   4.17   1.20          1.29  12.42  2.44
17         1      5694   0.02   0.19    

In [770]:
X = dataset.iloc[:,1:5].values
y = dataset.iloc[:, 5:].values

In [771]:
print(X)

[[1.60e+03 2.69e+00 5.60e-01 1.71e+00]
 [1.44e+03 5.29e+00 6.40e-01 2.18e+00]
 [3.67e+03 1.32e+00 1.17e+00 1.46e+00]
 [3.01e+03 7.70e-01 1.19e+00 1.56e+00]
 [4.93e+03 1.40e-01 5.20e-01 1.52e+00]
 [5.32e+03 1.00e-01 1.00e-01 4.90e-01]
 [3.55e+03 1.67e+00 5.10e-01 2.50e-01]
 [3.30e+03 2.60e-01 1.01e+00 1.61e+00]
 [6.32e+03 3.90e-01 8.00e-02 4.50e-01]
 [4.42e+03 3.40e-01 1.95e+00 2.43e+00]
 [1.74e+03 4.55e+00 1.26e+00 2.76e+00]
 [3.83e+03 4.72e+00 1.25e+00 1.73e+00]
 [2.44e+03 1.75e+00 1.09e+00 3.29e+00]
 [4.83e+03 1.46e+00 4.80e-01 2.30e-01]
 [3.74e+03 1.18e+00 1.12e+00 1.46e+00]
 [3.85e+03 4.81e+00 9.30e-01 1.63e+00]
 [4.74e+03 4.17e+00 1.20e+00 1.29e+00]
 [5.69e+03 2.00e-02 1.90e-01 2.80e-01]
 [5.70e+03 6.70e-01 6.80e-01 4.70e-01]
 [5.80e+03 3.20e-01 3.90e-01 5.90e-01]
 [1.68e+03 1.46e+00 9.80e-01 4.64e+00]
 [1.36e+03 4.00e-02 1.60e-01 3.00e-01]
 [4.27e+03 1.01e+00 9.70e-01 6.40e-01]
 [3.44e+03 9.40e-01 7.90e-01 3.87e+00]
 [1.65e+03 1.21e+00 9.80e-01 4.59e+00]
 [1.86e+03 2.78e+00 1.03e

In [772]:
print(y)

[[10.13  1.69]
 [ 8.5   1.44]
 [11.09  2.08]
 [13.66  2.06]
 [15.77  2.65]
 [16.86  2.11]
 [15.32  2.43]
 [12.92  2.35]
 [17.55  2.62]
 [12.41  2.43]
 [ 9.7   2.28]
 [11.1   2.01]
 [11.69  1.61]
 [15.13  2.08]
 [ 9.37  1.95]
 [14.49  2.58]
 [12.42  2.44]
 [16.86  2.34]
 [16.49  2.42]
 [15.35  2.3 ]
 [10.51  1.57]
 [14.58  1.83]
 [13.22  1.95]
 [13.97  2.28]
 [10.31  2.13]
 [ 9.08  1.8 ]
 [ 8.34  1.65]
 [ 3.98  0.94]
 [ 2.69  0.78]
 [ 4.88  0.82]
 [ 3.28  0.78]
 [ 2.69  1.  ]
 [ 4.82  0.91]
 [ 4.01  0.89]
 [ 2.19  0.96]
 [ 0.94  1.36]
 [ 3.34  1.04]
 [ 2.12  0.8 ]
 [ 1.67  1.01]
 [ 3.6   0.94]
 [ 6.03  0.93]
 [ 4.81  0.99]
 [ 1.99  0.87]
 [ 3.01  1.05]
 [ 2.44  0.86]
 [ 3.59  0.83]
 [ 5.    0.96]
 [ 1.86  0.88]
 [ 1.77  0.82]
 [ 3.91  0.9 ]]


In [773]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [774]:
print(X_test)

[[1.65e+02 1.05e+01 3.26e+00 5.49e+00]
 [3.83e+03 4.72e+00 1.25e+00 1.73e+00]
 [1.74e+03 4.55e+00 1.26e+00 2.76e+00]
 [1.23e+02 6.40e+00 6.50e+00 1.01e+01]
 [3.67e+03 1.32e+00 1.17e+00 1.46e+00]
 [1.21e+02 1.03e+01 6.26e+00 5.27e+00]
 [7.30e+01 6.30e+00 5.80e+00 8.81e+00]
 [9.10e+01 5.96e+00 7.31e+00 9.36e+00]
 [4.27e+03 1.01e+00 9.70e-01 6.40e-01]
 [4.93e+03 1.40e-01 5.20e-01 1.52e+00]
 [3.90e+01 7.50e+00 8.60e+00 4.39e+00]
 [1.09e+02 1.04e+01 6.60e+00 4.95e+00]
 [1.77e+03 5.00e+00 1.51e+00 1.12e+00]]


In [775]:
#FEATURE SELECTION
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

In [776]:
import tensorflow as tf

In [777]:
## Initializing the ANN
ann = tf.keras.models.Sequential()

In [778]:
### Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=40, activation='tanh'))


In [779]:
### Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=40, activation='tanh'))

In [780]:
### Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=40, activation='tanh'))

In [781]:
### Adding the output layer
ann.add(tf.keras.layers.Dense(units=2))

In [782]:
### Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [783]:
### Training the ANN model on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 800)

Epoch 1/800
2/2 [==============================] - 0s 3ms/step - loss: 57.2707
Epoch 2/800
2/2 [==============================] - 0s 3ms/step - loss: 53.6770
Epoch 3/800
2/2 [==============================] - 0s 4ms/step - loss: 47.8726
Epoch 4/800
2/2 [==============================] - 0s 3ms/step - loss: 41.8907
Epoch 5/800
2/2 [==============================] - 0s 3ms/step - loss: 37.9546
Epoch 6/800
2/2 [==============================] - 0s 3ms/step - loss: 34.8668
Epoch 7/800
2/2 [==============================] - 0s 3ms/step - loss: 32.2929
Epoch 8/800
2/2 [==============================] - 0s 3ms/step - loss: 29.4485
Epoch 9/800
2/2 [==============================] - 0s 6ms/step - loss: 26.8165
Epoch 10/800
2/2 [==============================] - 0s 3ms/step - loss: 24.7900
Epoch 11/800
2/2 [==============================] - 0s 3ms/step - loss: 23.0170
Epoch 12/800
2/2 [==============================] - 0s 3ms/step - loss: 21.7436
Epoch 13/800
2/2 [==============================]

In [784]:
from ann_visualizer.visualize import ann_viz;


ann_viz(ann, view=True)

In [785]:
### Predicting the results of the Test set
y_pred = ann.predict(X_train)
np.set_printoptions(precision=2)
y_pred

array([[ 2.08,  0.85],
       [13.3 ,  2.09],
       [13.3 ,  2.09],
       [13.3 ,  2.09],
       [ 3.7 ,  0.84],
       [ 2.79,  0.89],
       [ 4.66,  0.93],
       [13.3 ,  2.09],
       [ 3.37,  0.85],
       [ 4.8 ,  0.85],
       [13.3 ,  2.09],
       [ 2.05,  0.85],
       [13.3 ,  2.09],
       [ 3.12,  0.95],
       [13.3 ,  2.09],
       [13.3 ,  2.09],
       [13.3 ,  2.09],
       [13.3 ,  2.09],
       [13.3 ,  2.09],
       [ 6.03,  0.91],
       [ 3.71,  0.9 ],
       [13.3 ,  2.09],
       [13.3 ,  2.09],
       [ 2.16,  0.85],
       [13.3 ,  2.09],
       [13.3 ,  2.09],
       [13.3 ,  2.09],
       [ 2.57,  0.88],
       [13.3 ,  2.09],
       [13.3 ,  2.09],
       [13.3 ,  2.09],
       [ 3.88,  0.94],
       [ 5.01,  0.93],
       [13.3 ,  2.09],
       [13.3 ,  2.09],
       [ 1.9 ,  0.89],
       [ 2.62,  0.85]], dtype=float32)

In [786]:
concat2=np.column_stack((X_train,y_pred))
df2 = pd.DataFrame(concat2)
display(df2)

0      1      2      3          4         5
0     84.0   5.10   7.90   4.69   2.084016  0.850902
1   5700.0   0.67   0.68   0.47  13.300170  2.091985
2   3305.0   0.26   1.01   1.61  13.300173  2.091986
3   3740.0   1.18   1.12   1.46  13.300171  2.091985
4     66.0   6.90  10.70   4.82   3.700284  0.836774
5     94.0   6.80   8.80   7.42   2.792177  0.886667
6     87.0   5.12   4.34   3.54   4.659208  0.926857
7   3846.0   4.81   0.93   1.63  13.300170  2.091985
8     26.0   5.18   7.25   3.95   3.374770  0.851196
9     45.0   5.70  10.40   3.68   4.795132  0.852027
10  4739.0   4.17   1.20   1.29  13.300170  2.091985
11    39.0   7.80  12.60  12.38   2.054020  0.845358
12  1684.0   1.46   0.98   4.64  13.300195  2.091989
13    65.0  10.30   8.80   8.36   3.123302  0.951779
14  6318.0   0.39   0.08   0.45  13.300170  2.091985
15  4832.0   1.46   0.48   0.23  13.300170  2.091985
16  1857.0   2.78   1.03   1.91  13.300263  2.092019
17  5320.0   0.10   0.10   0.49  13.300170  2.091985
18  5694.0   0.02   0.19   0.28  13.300170  2.091985
19   111.0  15.10  13.80   9.43   6.029466  0.910332
20   125.0   8.10   7.50   9.78   3.709702  0.900717
21  1436.0   5.29   0.64   2.18  13.300314  2.092039
22  2435.0   1.75   1.09   3.29  13.300179  2.091988
23   121.0   2.80   8.50   3.08   2.164437  0.848434
24  1649.0   1.21   0.98   4.59  13.300200  2.091988
25  3546.0   1.67   0.51   0.25  13.300172  2.091986
26  3439.0   0.94   0.79   3.87  13.300170  2.091985
27    96.0   6.60   9.20   7.67   2.567105  0.881353
28  1355.0   0.04   0.16   0.30  13.302582  2.092869
29  5800.0   0.32   0.39   0.59  13.300170  2.091985
30  4420.0   0.34   1.95   2.43  13.300170  2.091985
31   109.0   9.00   5.50   6.89   3.879839  0.943234
32    24.0   8.40   9.30   7.45   5.007261  0.934343
33  3013.0   0.77   1.19   1.56  13.300176  2.091988
34  1598.0   2.69   0.56   1.71  13.300413  2.092075
35    37.0   7.30   5.10   8.37   1.904441  0.888612
36   140.0   7.90   9.90   5.31   2.622519  0.850590

In [787]:
#PREDICTING A NEW RESULT
print(ann.predict(sc.transform([[6318,0.38,0.08,0.45]])))

[[10.82  1.29]]


In [788]:
#PREDICTING A NEW RESULT
print(ann.predict(sc.transform([[1744,4.55,1.26,2.76]])))

[[2.02 0.21]]


In [789]:
from sklearn.metrics import mean_squared_error as MSE 
rmse = np.sqrt(MSE(y_train, y_pred)) 
print("RMSE : % f" %(rmse)) 

RMSE :  1.473369


In [790]:
from sklearn.metrics import r2_score 
r2 = r2_score(y_train, y_pred) 
print("R^2 : % f" %(r2))

R^2 :  0.847000


In [791]:
### Predicting the results of the Test set
y_pred2 = ann.predict(X_test)
np.set_printoptions(precision=2)
y_pred2

array([[ 6.53,  1.02],
       [13.3 ,  2.09],
       [13.3 ,  2.09],
       [ 3.63,  0.92],
       [13.3 ,  2.09],
       [ 4.32,  0.9 ],
       [ 2.39,  0.98],
       [ 2.63,  0.96],
       [13.3 ,  2.09],
       [13.3 ,  2.09],
       [ 4.47,  0.9 ],
       [ 4.21,  0.91],
       [13.3 ,  2.09]], dtype=float32)

In [792]:
concat=np.column_stack((X_test,y_pred2))
df = pd.DataFrame(concat)
display(df)

0      1     2      3          4         5
0    165.0  10.53  3.26   5.49   6.534306  1.015040
1   3832.0   4.72  1.25   1.73  13.300170  2.091985
2   1744.0   4.55  1.26   2.76  13.300216  2.092001
3    123.0   6.40  6.50  10.11   3.633150  0.915264
4   3672.0   1.32  1.17   1.46  13.300171  2.091985
5    121.0  10.27  6.26   5.27   4.315477  0.901680
6     73.0   6.30  5.80   8.81   2.393604  0.980973
7     91.0   5.96  7.31   9.36   2.632099  0.959163
8   4266.0   1.01  0.97   0.64  13.300170  2.091985
9   4934.0   0.14  0.52   1.52  13.300170  2.091985
10    39.0   7.50  8.60   4.39   4.472493  0.899103
11   109.0  10.40  6.60   4.95   4.206517  0.908456
12  1769.0   5.00  1.51   1.12  13.300283  2.092028